
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { CheckCircle } from 'lucide-react';

interface TasksListProps {
  tasks: string[];
}

const TasksList: React.FC<TasksListProps> = ({ tasks }) => {
  if (tasks.length === 0) {
    return (
      <Card className="shadow-lg border-0 bg-card">
        <CardHeader className="bg-gradient-to-r from-secondary to-accent text-foreground">
          <CardTitle className="text-xl font-semibold flex items-center gap-2">
            <CheckCircle className="w-5 h-5" />
            Generated Tasks
          </CardTitle>
          <p className="text-muted-foreground">Tasks will appear here after processing your transcript</p>
        </CardHeader>
        <CardContent className="p-6">
          <div className="text-center py-8">
            <div className="w-16 h-16 mx-auto mb-4 bg-muted rounded-full flex items-center justify-center">
              <CheckCircle className="w-8 h-8 text-muted-foreground" />
            </div>
            <p className="text-muted-foreground">No tasks generated yet</p>
            <p className="text-sm text-muted-foreground mt-1">Submit a meeting transcript to get started</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="shadow-lg border-0 bg-card">
      <CardHeader className="bg-gradient-to-r from-secondary to-accent text-foreground">
        <CardTitle className="text-xl font-semibold flex items-center gap-2">
          <CheckCircle className="w-5 h-5" />
          Generated Tasks
          <Badge variant="secondary" className="ml-auto bg-background/20 text-foreground">
            {tasks.length} {tasks.length === 1 ? 'task' : 'tasks'}
          </Badge>
        </CardTitle>
        <p className="text-muted-foreground">AI-generated action items from your meeting</p>
      </CardHeader>
      <CardContent className="p-6">
        <div className="space-y-3">
          {tasks.map((task, index) => (
            <div
              key={index}
              className="flex items-start gap-3 p-4 rounded-lg bg-muted/30 border border-border/50 hover:bg-muted/50 transition-colors duration-200"
            >
              <div className="flex-shrink-0 w-6 h-6 rounded-full bg-primary text-primary-foreground text-sm font-semibold flex items-center justify-center mt-0.5">
                {index + 1}
              </div>
              <p className="text-foreground flex-1 leading-relaxed">
                {task}
              </p>
            </div>
          ))}
        </div>
        
        <div className="mt-6 p-4 bg-accent/20 rounded-lg border border-accent/30">
          <p className="text-sm text-muted-foreground">
            💡 <strong>Tip:</strong> These tasks were generated by AI based on your meeting transcript. 
            Review and modify them as needed for your specific workflow.
          </p>
        </div>
      </CardContent>
    </Card>
  );
};

export default TasksList;
